# clamd.conf
# (Based on your original)
LogFile /dev/stdout
LogFileLocking false

LogTime yes
LogClean yes
LogVerbose yes

LocalSocket /var/run/clamav/clamd.sock
TCPSocket 3310
TCPAddr 127.0.0.1

MaxConnectionQueueLength 30
ReadTimeout 300
StreamMaxLength 50M
