[supervisord]
nodaemon=true
user=appuser
logfile=/dev/stdout
logfile_maxbytes=0

[program:clamd]
command=clamd --foreground=true --config-file=/etc/clamav/clamd.conf
autorestart=true
startretries=5
user=clamav
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:app]
command=gunicorn -b :8080 --workers=2 --timeout 300 scanner:app
autorestart=true
user=appuser
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PORT=8080